'''
f = open(filename,mode)
line=f.read()
line=f.readlines()
f.write(line)
f.writelines(line)

f.close()
'''
f = open('tem.dat','r+b')
p=f.tell()
print('Position at ',p)
f.seek(5,0)
p=f.tell()
print('Position at ',p)
f.seek(12,0)
p = f.tell()
print('Position at ',p)
data=f.read(4)
print('data is ',data)
print('Data is ',data.decode('utf-8'))
f.seek(12,1)
p=f.tell()
print('Position at ',p)
f.seek(5,2)
p=f.tell()
print('Position at ',p)
f.seek(-5,2)
p=f.tell()
print('Position at ',p)

f.write(b'Ajay')
p=f.tell()
print('Position at ',p)
f.close()

