import my_module
print(my_module.l)
print(my_module.list)
print(my_module.dis)
A = my_module.Rectangle(3,4)
a = A.area()
print(a)
p = A.perimeter()
print(p)
N = my_module.Employee('asd','kumar','asf',123,10000)
print(N)
a = N.getsalary()
print(a)
d = N.fullname()
print(d)
f = N.getmail()
print(f)
from my_module import Person
Q = Person('duggu','kunal','@gmail')
print(Q)